# =============================================================================
# Composite Action: Docker Build + Optional Trivy Scan
# =============================================================================
# Centralized Docker image build with GHA cache (mode=max) and optional
# Trivy vulnerability scanning.
# =============================================================================

name: Docker Build & Scan
description: Build Docker image with Buildx cache and optional Trivy scan

inputs:
  context:
    description: Docker build context path
    required: true
  dockerfile:
    description: Path to Dockerfile
    required: true
  image-name:
    description: Image tag name (e.g. ralphe/cms)
    required: true
  tag-suffix:
    description: Tag suffix (e.g. ci-abc1234)
    required: true
  scan:
    description: Run Trivy vulnerability scan
    required: false
    default: 'false'
  push:
    description: Push image to registry
    required: false
    default: 'false'

outputs:
  image-digest:
    description: Built image digest
    value: ${{ steps.build.outputs.digest }}
  scan-report-path:
    description: Path to Trivy scan report (if scan enabled)
    value: ${{ steps.scan.outputs.report-path }}

runs:
  using: composite
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3.6.1

    - name: Build image
      id: build
      uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.4.0
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        push: ${{ inputs.push == 'true' }}
        load: ${{ inputs.push != 'true' }}
        tags: ${{ inputs.image-name }}:${{ inputs.tag-suffix }}
        cache-from: type=gha,scope=${{ inputs.image-name }}
        cache-to: type=gha,mode=max,scope=${{ inputs.image-name }}

    - name: Trivy vulnerability scan
      id: scan
      if: inputs.scan == 'true'
      shell: bash
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
        REPORT_PATH="trivy-$(echo '${{ inputs.image-name }}' | tr '/' '-').sarif"
        trivy image --format sarif --output "$REPORT_PATH" \
          --severity CRITICAL,HIGH --ignore-unfixed \
          "${{ inputs.image-name }}:${{ inputs.tag-suffix }}" || true
        echo "report-path=$REPORT_PATH" >> $GITHUB_OUTPUT
