#!/usr/bin/env bash
set -euo pipefail

COMPOSE_FILE="${1:-docker-compose.hostinger.prod.yml}"
ENV_OUT="${2:-.env.workflow_ids.generated}"

echo "== Generating workflow IDs from Postgres =="
echo "Using compose: $COMPOSE_FILE"

# Query workflow ids by name
q() {
  local name="$1"
  docker compose -f "$COMPOSE_FILE" exec -T postgres psql -U n8n -d n8n -Atc \
    "select id from workflow_entity where name = '$name' order by id desc limit 1;"
}

core_id="$(q "W4 - CORE Agent (State + Voice + Secure)")"

if [[ -z "${core_id}" ]]; then
  echo "❌ CORE workflow not found. Import workflows first, then rerun."
  exit 1
fi

cat > "$ENV_OUT" <<EOF
# Generated by scripts/generate_workflow_ids.sh
CORE_WORKFLOW_ID=${core_id}
EOF

echo "✅ Wrote $ENV_OUT"
echo "Next: source it or copy into .env"
