# =============================================================================
# Composite Action: Health Check with Retry
# =============================================================================
# Polls a health endpoint with configurable retries, measures response time,
# and annotates GitHub on failure.
# =============================================================================

name: Health Check
description: Poll health endpoint with retries and response time measurement

inputs:
  url:
    description: Health check URL
    required: true
  max-retries:
    description: Maximum number of retry attempts
    required: false
    default: '15'
  retry-interval:
    description: Seconds between retries
    required: false
    default: '10'
  expected-code:
    description: Expected HTTP status code
    required: false
    default: '200'

outputs:
  status:
    description: Health check result (healthy|unhealthy)
    value: ${{ steps.check.outputs.status }}
  http-code:
    description: Last HTTP response code
    value: ${{ steps.check.outputs.http_code }}
  response-time-ms:
    description: Response time in milliseconds
    value: ${{ steps.check.outputs.response_time_ms }}

runs:
  using: composite
  steps:
    - name: Poll health endpoint
      id: check
      shell: bash
      run: |
        RETRY=0
        MAX_RETRIES=${{ inputs.max-retries }}
        INTERVAL=${{ inputs.retry-interval }}
        EXPECTED=${{ inputs.expected-code }}
        URL="${{ inputs.url }}"

        while [ $RETRY -lt $MAX_RETRIES ]; do
          START_MS=$(date +%s%N)

          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" \
            --connect-timeout 10 --max-time 30 \
            "$URL" || echo "000")

          END_MS=$(date +%s%N)
          ELAPSED_MS=$(( (END_MS - START_MS) / 1000000 ))

          if [ "$HTTP_CODE" = "$EXPECTED" ]; then
            echo "status=healthy" >> $GITHUB_OUTPUT
            echo "http_code=$HTTP_CODE" >> $GITHUB_OUTPUT
            echo "response_time_ms=$ELAPSED_MS" >> $GITHUB_OUTPUT
            echo "Health check passed (HTTP $HTTP_CODE, ${ELAPSED_MS}ms)"
            exit 0
          fi

          RETRY=$((RETRY + 1))
          echo "Attempt $RETRY/$MAX_RETRIES: HTTP $HTTP_CODE (${ELAPSED_MS}ms)"
          sleep $INTERVAL
        done

        echo "status=unhealthy" >> $GITHUB_OUTPUT
        echo "http_code=$HTTP_CODE" >> $GITHUB_OUTPUT
        echo "response_time_ms=$ELAPSED_MS" >> $GITHUB_OUTPUT
        echo "::error::Health check failed after $MAX_RETRIES attempts (last HTTP $HTTP_CODE)"
        exit 1
